apm-server:
  host: "localhost:8200"
  rum:
    enabled: true
  auth:
    anonymous:
      allow_service: [calorie_app]

output:
  elasticsearch:
    hosts: localhost:9200

queue.mem.events: 4096

max_procs: 4